### ISSUE TITLE
GetMessageAsync без CompleteMessage может не завершить сообщение в RabbitMQ

### ISSUE THREAD

**Issue by Rinatich** [Byndyusoft/Byndyusoft.Net.RabbitMq#12]
Есть два варианта решения:
1. Делать наследника, при dispose которого nack'ать сообщение. Он будет содержать внутри себя информацию о клиенте рэббита.
2. Возвращать класс, который управляет временем жизни сообщения. Внутри себя содержит информацию о сообщении и клиенте рэббита. Также при dispose которого nack'ается сообщение.

**Comment by Mblkolo** [comment]
3. Отдать решение этой ситуации прикладному программисту. Т.к. апи достаточно низкоуровневое, программист должен осознавать риски. Чтобы рисков не было, он может использовать метод подписи, который вызывает обработку колбэком.

**Comment by Rinatich** [comment]
@govorovvs поправил

**Comment by Rinatich** [comment]
@govorovvs поправил с использованием 1-го варианта
