### ISSUE TITLE
NuGet-пакет для работы с RabbitMq

### ISSUE THREAD

**Issue by myasnik0v** [Byndyusoft/Byndyusoft.Net.RabbitMq#3]
Необходима следующая функциональность
- [x] Инициализация очередей
- [x] Работа с несколькими очередями и обменниками в одном приложении
- [x] Поддержка трасировки
- [x] Расширяемые стратегии по работе с ошибками (очерди ошибок, отложенная обработка и т.д.)
- [x] Возможность указать хэндлер для обработки вернувшихся сообщений
- [x] Поддержка сбора метрик обработки сообщений
- [x] Валидация имен очередей
- [x] Типизованное чтение
- [x] Конфигурирование отправки сообщений в зависимости от их типов
- [x] Переотправка ошибочных сообщений
- [x] Хочется легкого мока, поведение которого потом можно будет легко валидировать

**Comment by litichevskiydv** [comment]
05.04 Планируем выложить текущие наработки в паблик + добавить поддержку сбора метрик

**Comment by litichevskiydv** [comment]
За майские описываем контракт и Readme и закидываем в паблик

**Comment by litichevskiydv** [comment]
Скинули интерфейс в канал #dotnet, сейчас ждем фидбека

**Comment by litichevskiydv** [comment]
Сегодня накидаем дальнейший план  по работам в свете приближающегося релиза

**Comment by litichevskiydv** [comment]
Хочется легкого мока, поведение которого потом можно будет легко валидировать

**Comment by litichevskiydv** [comment]
В пятницу решаем по дальнейшим планам

**Comment by litichevskiydv** [comment]
Пока работы на паузе, мы ищем варианты зарелизиться и продолжить работы над пакетом

**Comment by litichevskiydv** [comment]
Сегодня Илья и Дима зафиксируют контракт, после этого наметим роадмап

**Comment by litichevskiydv** [comment]
До конца недели накидываем fluent Api для настройки обменников и очередей

**Comment by govorovvs** [comment]
я бы везде сделал неймспейс `Byndyusoft.Net.RabbitMq`

**Comment by litichevskiydv** [comment]
В слаке лежит PR, ждущий ревью. Сейчас готово описание API для
1. Настройки топологии
2. Продьюсеров
3. Консьюмеров

**Comment by litichevskiydv** [comment]
Начинаем имплементацию контрактов

**Comment by litichevskiydv** [comment]
Реализуем структуру данных конфигуратора топологии, планируем закончить на этой неделе.
На следующей неделе - создание очередей и биндинг

**Comment by litichevskiydv** [comment]
Реализованы конфигуратор и конфигурация топологии, в конфигурации остались только мидлвары, пайпы используем при обработки ошибок.
В планах - создание топологии

**Comment by AntonyNET** [comment]
Сделал паблиш и консьюм, ресенд ошибок. На неделю возьму обработку вернувшихся сообщений и обработку ошибок при обработке входящего сообщения.

**Comment by litichevskiydv** [comment]
Сделана обработка ошибок + обработка вернувшихся сообщений.
В ближайшее время берем задачу по легкому моку.

**Comment by litichevskiydv** [comment]
Пока на Инфинитум.СОД релиз, масштабных работ не планируется. Возможно, на следующей неделе выпустим алфу и потестим ее на Инфинитум.МПК

**Comment by litichevskiydv** [comment]
Ждем, когда Дима Кожевников сможет вернуться к задаче

**Comment by litichevskiydv** [comment]
Нет подвижек, пока идет релиз на Инфинитум'е

**Comment by litichevskiydv** [comment]
В следующую среду ждем метрики+моки и бета-пакетик

**Comment by litichevskiydv** [comment]
Планы:
1. Заиспользовать пакет @AntonyNET для работы с телеметрией
1.5. Проводим codereview 
2. Делаем alpha-версию (через 2-3 недели)

**Comment by litichevskiydv** [comment]
Добавлены метрики и расширения для их подключения.
@govorovvs поможет с публикацией пакета
+ на следующей неделе сделаем внутреннюю встречу-ревью

**Comment by litichevskiydv** [comment]
К следующей среде планируем пофиксить замечания и выпустить альфу

**Comment by litichevskiydv** [comment]
Осталось починить сборку и выпустить кубик

**Comment by litichevskiydv** [comment]
Сегодня посмотрим за pipeline и решим, когда выпускаем версию

**Comment by litichevskiydv** [comment]
Планируем добавить пакет в шаблон воркера до конца января

**Comment by litichevskiydv** [comment]
Шаблон выпускаем не раньше конца февраля-начала марта

**Comment by litichevskiydv** [comment]
Обсудим с @myasnik0v, когда сможем подступиться к воркеру

**Comment by litichevskiydv** [comment]
Сегодня отпишемся о конкретике

**Comment by litichevskiydv** [comment]
В конце следующей недели в работу пойдет шаблон воркера

**Comment by litichevskiydv** [comment]
Ориентировочно 02.03 приступим к разработке шаблона воркера

**Comment by litichevskiydv** [comment]
Ориентировочно 02.03 приступим к разработке шаблона воркера

**Comment by litichevskiydv** [comment]
Ждем фидбека от @govorovvs

**Comment by litichevskiydv** [comment]
@YuriyatByndyusoft завиксирует фидбек в карточке, чтобы Витя посмотрел по ыходу из отпуска

**Comment by YuriyatByndyusoft** [comment]
Фидбэк (по ветке feature/wip):

- ExchangeType.Funout - опечатка, Fanout
- ClientFactoryExample - из примера неочевидна связь с named options (RabbitMqClientOptions), требуется проваливаться внутрь фабрик, чтобы понять это. Думаю, стоит это явно показывать (в ридми / в самом примере)
- Если в проекте нет явной/неявной зависимости от NewtonSoft.Json, будет выкидываться исключение: System.InvalidOperationException: 'Newtonsoft.Json assembly is not found. Starting from EasyNetQ v7, an explicit dependency from Newtonsoft.Json was removed. Please reference Newtonsoft.Json package (directly or indirectly) or add one of EasyNetQ.Serialization.* packages instead.' На данный момент есть только одна реализация: EasyNetQ.Serialization.NewtonsoftJson, которую можно добавить в Byndyusoft.Messaging.RabbitMq (https://github.com/EasyNetQ/EasyNetQ/releases/tag/7.0.0).
- RabbitMqConsumerRetryExtensions.WithConstantTimeoutRetryStrategy - если параметр QueueOptions == null, то delay игнорируется (используется 60 сек), consumer.WithDeclareQueue не вызывается (при ретрае отрабатывает RabbitMqClientHandlerExtensions.PublishMessageToRetryQueueAsync, который создаёт ретрай очередь, если она не существует с messageTtl == 1 мин)
может быть поменять в методе расширения `if (options is not null) {...}`
на
```
var retryQueueOptions =
	options is null
		? QueueOptions.Default
			.WithMessageTtl(delay)
			.WithDeadLetterExchange(null)
			.WithDeadLetterRoutingKey(consumer.QueueName)
		: options
			.WithMessageTtl(delay)
			.WithDeadLetterExchange(null)
			.WithDeadLetterRoutingKey(consumer.QueueName);

consumer.WithDeclareQueue(retryQueueName, retryQueueOptions);
```
- RabbitMqClientServiceCollectionExtensions.AddRabbitMqClient, почему services.AddSingleton, а не services.TryAddSingleton?

**Comment by litichevskiydv** [comment]
Релизим на следующей неделе

**Comment by litichevskiydv** [comment]
В декабре ждем рассказ от @govorovvs
